### PR TITLE
Add Amazon Linux 2  202002 Support

### PR DESCRIPTION
**Pull request by fams**
This patch allow use this role in Amazon Linux 2

### CODE REVIEW

**Comment by fams** [comment]
This fix #89

**Comment by geerlingguy** [comment]
I maintain an `amazonlinux2` docker image for testing (https://github.com/geerlingguy/docker-amazonlinux2-ansible), so please also add that to the test suite in `.travis.yml`

**Comment by fams** [comment]
> I maintain an `amazonlinux2` docker image for testing (https://github.com/geerlingguy/docker-amazonlinux2-ansible), so please also add that to the test suite in `.travis.yml`

how can i do it? Just another molecule distro?
Thanks

**Comment by fams** [comment]
It will not work with varnish 6 due to lack of jemalloc. The only way to add jemalloc is to enable a pack on extras with comamnd:
sudo amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
Unfortunately, it will make the system incompatible with php 5, 7.1, 7.3 and 7.4

**Pull request closed without merging**
