### PR TITLE
Fixes #109, Fixes #110, Fixes #111

### LINKED ISSUE #109: Ubuntu: install from the default repo instead of packagecloud
Hello,
I can’t find any varnish package on packagecloud for Ubuntu Jammy: https://packagecloud.io/app/varnishcache/varnish66/search?dist=ubuntu/jammy
However there is one in the default Ubuntu packages repo: https://packages.ubuntu.com/jammy/varnish
Am I missing something? If not, is there a possibility to force this role not to use packagecloud?
Thanks

### LINKED ISSUE #110: systemd unit file in wrong location leads to problems after package updates
Hi,

currently the role installs the systemd unit file in `/lib/systemd/system`, overwriting the existing file coming with the Debian package.

When updating Varnish, this file gets replaced by the package, resulting in potential startup errors because e.g. `-p 'vcc_allow_inline_c=on'` (via `varnishd_extra_options`) is no longer there. Varnish will then quit with VCL errors, when the VCL in place requires inline C support.

The correct place for the role-maintained systemd unit file would be `/etc/systemd/system/varnish.service`.

Validated only for Debian but should also be true for RedHat.

### LINKED ISSUE #111: Role doesn't support installation of additional Varnish packages
On Debian systems, when using the distribution package, the Varnish modules are available in the `varnish-modules` package. VMODs are an important part of more complex Varnish configurations and currently the role does not support installing additional packages.

Although the vendor packages (packagecloud.io) don't include VMOD-support at all (it seems), it is possible to install them using the distribution packages - at least on Debian, I haven't verified if the RedHat distribution and/or vendor packages supply VMODs.

It would be great if this role would support an additional install of `varnish-modules` on Debian systems with distribution packages.

Related to https://github.com/geerlingguy/ansible-role-varnish/issues/109

### PR DESCRIPTION
**Pull request by adepretis**
- Support both vendor and distribution packages for Debian, depending on "varnish_apt_use_packagecloud" (#109)
- Install systemd unit in /etc/systemd/system for compatiblity after package updates (#110)
- Support installation of additional module package, e.g. for Debian "varnish-modules" (#111)

### CODE REVIEW

**Comment by adepretis** [comment]
Tested with Debian 10 (real system) and RedHat (via molecule).

**Comment by adepretis** [comment]
Any thoughts on this @geerlingguy?

**Comment by Bilge** [comment]
Can we get a 🏷️ tag for this?

**Comment by geerlingguy** [comment]
Sorry about that, here you go! https://github.com/geerlingguy/ansible-role-varnish/tree/3.3.2

**Comment by Bilge** [comment]
@adepretis Pretty sure the implementation of varnish-modules is completely broken (see #116).

**Pull request merged**
